name: Test and Deploy Hello World App

on: 
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Start local server
        run: npx http-server ./app -p 3000 &

      - name: Run Playwright test
        run: npx playwright test
      
      - name: Deploy Hello World App
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app
      
      - name: Send email alert to users
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deploy Automation Alert"
          body: "Test and Deploy workflow completed with status: ${{ job.status }}"
          to: lalithareddy711@gmail.com, keerthybreddy@gmail.com
          from: "Keerthy Reddy <keerthybreddy@gmail.com>"
      
      - name: Send slack alert to users
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Test and Deploy workflow completed with status --> $JOB_STATUS"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          JOB_STATUS: ${{ job.status }}